"""Typed, validated access to the committed ``data/*.json`` datasets.

This is the single boundary between the JSON on disk and the rest of the
pipeline. Builders load through ``load_*`` (typed model objects); compute
scripts persist through ``save_*`` (validate-on-write). Schemas live in
``schemas``; the file<->function mapping lives in ``repository``.
"""

from .repository import (
    DATA_DIR,
    REGISTRY,
    load_combos,
    load_constructor_standings,
    load_current_drivers,
    load_driver_races,
    load_model_eval,
    load_overdue,
    load_podigami,
    load_podiums,
    load_schedule,
    load_soulmates,
    load_unlikeliest,
    save_combos,
    save_constructor_standings,
    save_current_drivers,
    save_driver_races,
    save_model_eval,
    save_overdue,
    save_podigami,
    save_podiums,
    save_schedule,
    save_soulmates,
    save_unlikeliest,
)
from .schemas import (
    CalibrationBin,
    Chosen,
    Combo,
    Constructor,
    ConstructorStandings,
    CurrentDriver,
    CurrentDrivers,
    DriverRaceRow,
    DriverRaces,
    DriverRef,
    DriverStrength,
    EvalWindow,
    LadderRow,
    ModelEval,
    ModelParams,
    Overdue,
    OverdueParams,
    OverduePerDriver,
    OverdueTrio,
    Podigami,
    PodigamiCandidate,
    PodigamiParams,
    Podium,
    RaceRef,
    RoundRace,
    Schedule,
    ScheduleRace,
    SeasonDebut,
    SoulmateDriver,
    SoulmatePair,
    Soulmates,
    Unlikeliest,
    UnlikeliestParams,
    UnlikeliestPerDriver,
    UnlikeliestTrio,
)

__all__ = [
    # repository
    "DATA_DIR",
    "REGISTRY",
    "load_podiums",
    "save_podiums",
    "load_combos",
    "save_combos",
    "load_soulmates",
    "save_soulmates",
    "load_current_drivers",
    "save_current_drivers",
    "load_driver_races",
    "save_driver_races",
    "load_overdue",
    "save_overdue",
    "load_unlikeliest",
    "save_unlikeliest",
    "load_schedule",
    "save_schedule",
    "load_podigami",
    "save_podigami",
    "load_model_eval",
    "save_model_eval",
    "load_constructor_standings",
    "save_constructor_standings",
    # schemas
    "RaceRef",
    "DriverRef",
    "Podium",
    "Combo",
    "SoulmateDriver",
    "SoulmatePair",
    "Soulmates",
    "CurrentDriver",
    "CurrentDrivers",
    "DriverRaceRow",
    "DriverRaces",
    "OverduePerDriver",
    "OverdueTrio",
    "OverdueParams",
    "Overdue",
    "UnlikeliestPerDriver",
    "UnlikeliestTrio",
    "UnlikeliestParams",
    "Unlikeliest",
    "ScheduleRace",
    "Schedule",
    "PodigamiParams",
    "DriverStrength",
    "PodigamiCandidate",
    "RoundRace",
    "SeasonDebut",
    "Podigami",
    "EvalWindow",
    "ModelParams",
    "LadderRow",
    "Chosen",
    "CalibrationBin",
    "ModelEval",
    "Constructor",
    "ConstructorStandings",
]
